# Podfile
platform :ios, '11.0'
use_frameworks!

target 'ChhoeTaigi' do
    # Firebase
    pod 'Firebase/Core'
    pod 'Firebase/Performance'
    pod 'Fabric'
    pod 'Crashlytics'

    # Realm
    pod 'RealmSwift'

    # RxSwift
    pod 'RxSwift'
    pod 'RxCocoa'
end
