# Podfile
platform :ios, '10.0'
use_frameworks!

target 'ChhoeTaigi' do
    # Firebase
    pod 'Firebase/Core'
    pod 'Firebase/Performance'
    pod 'Fabric'
    pod 'Crashlytics'

    # Realm
    pod 'RealmSwift'

    # RxSwift
    pod 'RxSwift'
    pod 'RxCocoa'

    # Custom Segmented Control
    pod 'Segmentio', '~> 3.2'

end
